// leave your apiKey in
export const envApiKey = "xxxxxxxxxxxxx";
// leave your authDomain in
export const envAuthDomain = "xxxxxxxxxxxxx";
// leave your databeseURL in
export const envDatabeseURL = "xxxxxxxxxxxxx";
// leave your projectId in
export const envProjectId = "xxxxxxxxxxxxx";
// leave your storageBucket in
export const envStorageBucket = "xxxxxxxxxxxxx";
// leave your messagingSenderId in
export const envMessagingSenderId = "xxxxxxxxxxxxx";
// leave your appId in
export const envApiId = "xxxxxxxxxxxxx";